#+TITLE: CV Jeremy Alan
#+EMAIL: jeremy.electronic@protonmail.com
#+DESCRIPTION:
#+KEYWORDS:
#+SUBTITLE:
#+DATE: \today

#+AUTHOR: Jeremy Alan
#+EMAIL: jeremy.electronic@protonmail.com
#+LANGUAGE: en

:LATEX:
#+LATEX_CLASS: article
#+LATEX_HEADER: \usepackage[letterpaper, margin=2cm]{geometry}
#+LATEX_HEADER: \linespread{-0.50}
#+LATEX_HEADER: \parskip{-5pt}
#+LATEX_HEADER_EXTRA:
#+LATEX_COMPILER: pdflatex
#+LaTeX_HEADER: \usepackage{rmk_org_cv}
#+LaTeX_HEADER: \usepackage[T1]{fontenc}
#+LaTeX_HEADER: \usepackage{tgtermes}
#+LaTeX_HEADER: \usepackage[scale=.85]{tgheros}
#+LaTeX_HEADER: \usepackage{tgcursor}
#+LaTeX_HEADER: \renewcommand{\familydefault}{\sfdefault}
:END:

:OPTIONS:
#+OPTIONS: toc:nil H:10 ':t
#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t broken-links:nil c:nil creator:nil
#+OPTIONS: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+OPTIONS: timestamp:t title:t  |:t tags:nil
:END:

#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport long

#+CREATOR: Emacs 27.1 (Org mode 9.3)

#+BEGIN_QUOTE
I am a human software-writer primarily interested in building web applications using open source frameworks from the back-end to full-stack.  I have a soft spot for legible, well-documented code.

Most of my time is spent in a terminal window using emacs to build things which (hopefully!) make the world a better place in some way.

#+END_QUOTE

* Contact
** Name 
   Jeremy Alan
** Location
   Berlin, Berlin 10243, Germany
** Mobile
   +49 170 592 3415
** E-mail
   jeremy.electronic@protonmail.com
* Skillset
  :PROPERTIES:
  :CUSTOM_ID: knowledge
  :END:

** Languages
   JavaScript, Ruby, PHP
** Database Experience
   PostgreSQL, mySQL, mongodb
** Platform Experience
   *Frameworks*: node.js, Ruby on Rails, Laraval

   *Cloud Related*: AWS (Redshift, EC2, ELB, Lambda, VPC, awscli, API Gateway, CloudFormation), GCP (GKE, Cloud PubSub), serverless

   *CI/CD*: Jenkins-X (jx), ElasticBeanstalk
** Other Abilities / Tools
   command line (zsh, tmux, emacs, ssh) in *nix environments, monitoring (Grafana) & logging (CloudWatch, Splunk), documentation (markdown, wiki + Atlassian)

* People I've Worked With
  :PROPERTIES:
  :CUSTOM_ID: work-experience
  :END:

** 11/2017 - 7/2020
   [[https://myseiubenefits.org][SEIU 775 Benefits Group]]\\
   **Sr. Software Developer**

   First senior hire for a new agile development team focused on development of  an online learning-management system.  Provided team leadership during rapid expansion of the enterprise, including the addition of 5 additional developers.

   Architected and coded node.js microservices meshes on Kubernetes and ElasticBeanstalk utilizing an event-driven architecture via Cloud PubSub and SQS/SNS.

   Designed and implemented APIs from definition to API gateway, automating resource deployments to our VPC using CloudFormation templates (later serverless) to mitigate future waste.

   Improved team efficiency through guidance and mentorship of junior developers (eg. command line tools, CI/CD tooling, knowlegebases, or code-review), building instruction materials on a weekly basis.

** 05/2017 - 08/2017
   [[http://port80.com][Port80]]\\
   **Freelance Software Developer**

   Architected and built a node.js backend to integrate various StitchLabs (an e-commerce platform for supply chain management) with vendor distribution centers to connect small retailers to larger distribution systems.

   Overcame repeated challenges with the client's authentication systems intermittently failing to provide tokens, or expiring valid tokens.  Assisted their internal teams in reproducing and diagnosing the root cause, going past business hours as needed.

** 02/2012 - 01/2017
   [[https://fullcircle.com][Full Circle]]\\
   **Front End / Full-stack Developer**

   Architected and built our responsive single-page webapp using backbone.js (at the dawn of SPA's) to replace a legacy PHP site.  Public-facing functionality included member signup, shopping cart, account management, and seasonal promotions, leading to sustained growth from $6m to $16m over 3 years.

   Took lead on design, UX direction, and engineering of a full front-end toolset for distribution center management, to inform our produce-buyer decisions + input new products / inventory, and to support the in-house customer service team.  Worked closely with all relevant stakeholders to ensure their business needs were met or their processes were improved as a result.

   Employed TDD to ensure a reliable UI with minimal downtime through regular regression testing via Jasmine + Sinon.

** 08/2011 - 02/2012
  [[https://bluenile.com][Blue Nile]]\\
  **Developer, Front-End**

  Built new features as part of the Site Development team, such as filtering for Build Your Own Jewelry interface, or process improvements for laborious holiday site-theming.

  Maintained an aging JSP framework which was glued together with monolithic JS using jQuery.  

  Drove and developed a YAML-driven promotion engine to improve efficiency of adjusting the site with new business rules and to more easily allow for UAT to be completed on a short timeline from promotion details to deployment.

** 01/2011 - 06/2011
   [[http://ubm.com][United Business Media]]\\
   **Developer**

   Web application development, site maintenance, and event production for the [[https://blackhat.com][Black Hat]] brand.

   Built out event micro-sites for our events / conferences using a minimized toolset consisting of a static-site generator and a serious command of regular-expressions.

   Sole-developer on the first refactor of their CFP (call for papers) system from database design to implementation in Rails.

** 08/2008 - 11/2010
   [[http://avelle.com][Bag Borrow or Steal]]\\
   **Developer**

   Specialized in frontend development using Freemarker and JS (jQuery + Prototype) on a medium-scale enterprise stack (Java, Spring, Struts, and Hibernate on Tomcat).

   Heavily focused on exploratory work and prototyping of new features, such as improved quick-look / zoom within the product browse interface.

   Integrated a from-scratch interface with a backend API built out as part of a full migration of inventory to an in-house storage facility, the rollout of which had a hard deadline and where failure was not an option.

** 08/2007 - 08/2008
   *Volt*\\
   **Developer, Contract**

   Bugfix specialist on a large custom PHP app serving the medical billing industry. Wrote complicated ad-hoc mySQL queries against undocumented data sets in order to support current work and to aid in evaluation of cost/benefit analysis toward future projects.

* Project Highlights
  :PROPERTIES:
  :CUSTOM_ID: projects
  :END:

** LMS: API Gateway
   *SEIU 775*\\
   The Learning Management System is used by 60,000 union members and hundreds of instructors in order to train and certify in-home health care aids across the state.  It is a mission-critical, long-running, multi-faceted project requiring a high degree of coordination across departments.

   As a result of the need to consolidate / standardize on a single platform, the enterprise moved all services, repositories, etc. into AWS.  We implemented a VPC to house various databases and microservices which did not need external network access.

   I took the initiative on constructing our interface of these resources to public-facing frontends as well as developing an automated method for the rest of the team to more easily add new services + functionality without requiring a deep knowledge of the internals or risk of bringing down our gateway as a result of an issue during deployment.

   I utilized CloudFormation templates initially but eventually improved the process with serverless which helped more easily achieve the design goals.  Authentication during the first phase was handled with simple API keys.  I then laid the foundation for authentication via an identity provider at a later stage.  For integration testing I used Auth0 while the enterprise laid out future plans for Microsoft Azure.

** LMS: Block Scheduler
   *SEIU 775*\\
   Our instructors were spending an inordinate amount of time building out their sessions using a legacy custom interface within Salesforce.  We created a new service from the ground up utilizing React + Redux backed by nodejs.

   Upon handoff of the project specification, I developed the webapp frontend and supporting backend using stubs where necessary in order to demo basic user interaction sans persistance.  During the second phase of the project I focused primarily on backend integration with an external vendor who handled instructors' actions such as class rosters, scheduling, TODO research TO.  After a successful pass during user-acceptance testing, the result was presented to a wide audience within the organization and feedback was excellent.

** Predictive Analytics
   *SEIU 775*\\
   A member of the data team implemented a Python algorithm to generate a list of at-risk students in order to better facilitate retention of members / completion of our learning programs.  Upon departure of the author / data scientist, I was tasked with turning it into a deployment for use with a Kubernetes cluster through Docker.

   There was a minimal time window with which to get familiarized with the codebase's functionality and there were a number of challenges discovered when migrating it from its local Windows + Jupyter environment into the cloud in addition to bugfixes.

   After an intensive round of reworking some haphazardly implemented / inefficient algorithms, it was packaged up and given back to the data team for integration with their datasets.  Though I didn't receive the satisfaction of finalizing the deployment, it was still a personal highlight to overcome these unknown obstacles while learning the intricacies of a new framework in an unfamiliar language.

** Member Shopping SPA
   *Full Circle*\\
   A majority of my effort during my tenure was spent modernizing a problematic legacy PHP codebase and I was given a high degree of freedom to make technology decisions and design choices.  Single-page webapps were a relatively new paradigm at the onset of the project and the React ecosystem had not yet been firmly established so I made the decision to go with backbone.js due to its simplicity and ease of learning.

   I took the lead on moving our team forward with TDD methodology in order to ensure the reliability of the organization's most important system.  We had no design resources available in-house the contractors chosen by management gave us poor templates to build from so I requested that I work from my knowledge of UX principles (such as Krug's Don't Make Me Think) to develop interfaces of my own accord using Bootstrap.

   Using our style guide I integrated a responsive web experience for our shopping cart, member functions, subscription and payment flows (among others) with the in-progress Ruby backend at a rapid pace, oftentimes relying on mock data / responses as my development pace exceeded that of our backend developers.

   I actively engaged in process improvements to ensure the continued success of the team's development cycle and mentored my colleagues regarding our single-page app.  Upon launch we quickly overcame some unanticipated deployment issues, and afterward maintained a consistently reliable webapp for the remainder of my employment.

** Signup Process
   *Full Circle*\\
   The enterprise's signup flow presented us with some easy victories when transitioning to our JS-centric future.  There was a minimum of jQuery gluing together a set of PHP pages / poorly structured HTML.  Transitioning this to backbone.js allowed us to more readily maintain state, improve maintainability, and integrate with Google Analytics in order to make properly informed business decisions.

   I took initiative on turning comparison tests into accepted changes, a series of which ultimately resulted in a sustained increase in members reaching the goal-step.  My efforts focused on simplicity and a bit of marketing knowledge and one test in particular led us to a 30-percent increase within a single month.

* Education
  :PROPERTIES:
  :CUSTOM_ID: education
  :END:

** 08/2001 - 12/2002
   *University of Texas at Austin*

** 08/2005 - 12/2005
   *University of Texas at Austin*

* Interests
** Professional
   pushing the web forward (eg. WebAssembly, Rust), functional languages, infosec

** Other
   espresso, audio engineering, electronic music, race cars, simplicity
