#+TITLE: Jeremy Alan
#+EMAIL: jeremy.electronic@protonmail.com
#+DESCRIPTION:
#+KEYWORDS:
#+SUBTITLE:
#+DATE: \today

#+AUTHOR: Jeremy Alan
#+EMAIL: jeremy.electronic@protonmail.com
#+LANGUAGE: en

:LATEX:
#+LATEX_CLASS: article
#+LATEX_HEADER: \usepackage[letterpaper, margin=2cm]{geometry}
#+LATEX_HEADER: \linespread{0.85}
#+LATEX_HEADER_EXTRA:
#+LATEX_COMPILER: pdflatex
#+LaTeX_HEADER: \usepackage{jas_org_cv}
#+LaTeX_HEADER: \usepackage[T1]{fontenc}
#+LaTeX_HEADER: \usepackage{tgtermes}
#+LaTeX_HEADER: \usepackage[scale=.85]{tgheros}
#+LaTeX_HEADER: \usepackage{tgcursor}
#+LaTeX_HEADER: \renewcommand{\familydefault}{\sfdefault}
:END:

:OPTIONS:
#+OPTIONS: toc:nil H:10 ':t
#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t broken-links:nil c:nil creator:nil
#+OPTIONS: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+OPTIONS: timestamp:t title:t  |:t tags:nil
:END:

#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport long

#+CREATOR: Emacs 27.1 (Org mode 9.3)

* Contact
** Location
   Berlin, Germany (US citizen)
** Mobile
   +49 170 592 3415
** E-mail
   jeremy.electronic@protonmail.com
* Skillset
  :PROPERTIES:
  :CUSTOM_ID: knowledge
  :END:

** Languages
   JavaScript, Ruby, PHP
** Database Experience
   PostgreSQL, mySQL, mongodb
** Platform Experience
   *Frameworks*: node.js, Ruby on Rails, Laraval

   *Cloud Related*: AWS (Redshift, EC2, ELB, Lambda, VPC, awscli, API Gateway, CloudFormation), GCP (GKE, Cloud PubSub), serverless

   *CI/CD*: Jenkins-X (jx), ElasticBeanstalk
** Other Abilities / Tools
   command line (zsh, tmux, emacs, ssh) in *nix environments, monitoring (Grafana) & logging (CloudWatch, Splunk), documentation (markdown, wiki + Atlassian)

* Experience
  :PROPERTIES:
  :CUSTOM_ID: work-experience
  :END:

** 11/2017 - 7/2020
   [[https://myseiubenefits.org][SEIU 775 Benefits Group]]\\
   **Sr. Software Developer**

First senior hire for a new agile development team focused on development of  an online learning-management system.  Provided team leadership during rapid expansion of the enterprise, including the addition of 5 additional developers (while fully remote).

Architected and coded node.js microservices meshes on Kubernetes and ElasticBeanstalk utilizing an event-driven architecture via Cloud PubSub and SQS/SNS.

Designed and implemented APIs from definition to API gateway, automating resource deployments to our VPC using CloudFormation templates (later serverless) to mitigate future waste.

Improved team efficiency through guidance and mentorship of junior developers (eg. command line tools, CI/CD tooling, knowlegebases, or code-review), building instruction materials on a weekly basis.

** 05/2017 - 08/2017
   [[http://port80.com][Port80]]\\
   **Freelance Software Developer**

   Architected and built a node.js backend to integrate StitchLabs (an e-commerce platform for supply chain management) with various vendor distribution centers to connect small retailers to larger distribution systems.

   Overcame repeated challenges arising from intermittent failure in client authentication systems.  Assisted their internal teams in reproducing and diagnosing the root cause, going past business hours as needed.

** 02/2012 - 01/2017
   [[https://fullcircle.com][Full Circle]]\\
   **Front End / Full-stack Developer**

   Successfully replaced a legacy PHP site with a responsive single-page webapp using backbone.js (at the dawn of SPA's).  Public-facing functionality included member signup, shopping cart, account management, and seasonal promotions, leading to sustained growth from $6m to $16m over 3 years.

   Took lead on design, UX direction, and engineering of a full front-end toolset for distribution center management to inform our produce-buyer decisions + input new products / inventory, and to support the in-house customer service team.  Worked closely with all relevant stakeholders to ensure their business needs were met or their processes were improved as a result.

   Employed TDD to ensure a reliable UI with minimal downtime through regular regression testing via Jasmine + Sinon.

** 08/2011 - 02/2012
  [[https://bluenile.com][Blue Nile]]\\
  **Developer, Front-End**

  Built new features as part of the Site Development team, such as filtering for Build Your Own Jewelry interface, or process improvements for laborious holiday site-theming.

  Maintained an aging JSP framework which was glued together with monolithic JS using jQuery.  

  Drove and developed a YAML-driven promotion engine to improve efficiency of adjusting the site with new business rules and to more easily allow for UAT to be completed on a short timeline from promotion details to deployment.

** 01/2011 - 06/2011
   [[http://ubm.com][United Business Media]]\\
   **Developer**

   Web application development, site maintenance, and event production for the [[https://blackhat.com][Black Hat]] brand.

   Built out event micro-sites for our events / conferences using a minimized toolset consisting of a static-site generator and a serious command of regular-expressions.

   Sole-developer on the first refactor of their CFP (call for papers) system from database design to implementation in Rails.

** 08/2008 - 11/2010
   [[http://avelle.com][Bag Borrow or Steal]]\\
   **Developer**

   Specialized in frontend development using Freemarker and JS (jQuery + Prototype) on a medium-scale enterprise stack (Java, Spring, Struts, and Hibernate on Tomcat).

   Heavily focused on exploratory work and prototyping of new features, such as improved quick-look / zoom within the product browse interface.

   Integrated a from-scratch interface with a backend API built out as part of a full migration of inventory to an in-house storage facility, the rollout of which had a hard deadline and where failure was not an option.


* Education
  :PROPERTIES:
  :CUSTOM_ID: education
  :END:

** 08/2001 - 12/2002
   *University of Texas at Austin*

** 08/2005 - 12/2005
   *University of Texas at Austin*

* Interests
** Professional
   pushing the web forward (eg. WebAssembly, Rust, Flutter), functional languages, infosec, UX principles (eg. Krug)

** Other
   espresso, audio engineering, electronic music, race cars
